# unknown prometheus
global:
  # How frequently to scrape targets by default.
  scrape_interval: 1m

  # How long until a scrape request times out.
  scrape_timeout: 10s

  # How frequently to evaluate rules.
  evaluation_interval: 1m

  # The labels to add to any time series or alerts when communicating with
  # external systems (federation, remote storage, Alertmanager).
  external_labels:
    provider: "10.10.10.10" # change this

scrape_configs:
  - job_name: 'system_metrics'
  # where the prometheus node exporter agent is running to broadcast system metrics
    static_configs:
      - targets:
        - 10.216.151.128:9100
        - 10.216.151.62:9100
        - 10.216.151.23:9100

  - job_name: 'containers'
  # where the cadvisor container is running to broadcast the container's metrics
    static_configs:
      - targets:
        - 10.216.151.128:9091
        - 10.216.151.62:9091
        - 10.216.151.23:9091
