---
# playbook to deploy nginx docker container as a reverse proxy
- hosts: nginx
  gather_facts: yes
  become: yes
  tasks:
    - name: nginx directory
      file:
        path: /monitoring/nginx
        state: directory

    - name: nginx directory
      file:
        path: /monitoring/nginx/certs
        state: directory

    - name: copy nginx config file
      copy: src=nginx.conf dest=/monitoring/nginx/nginx.conf force=yes

    - name: copy certs
      copy: src=certs dest=/monitoring/nginx/ directory_mode=yes force=yes

    - name: nginx
      docker_container:
        name: nginx
        image: nginx
        state: started
        restart_policy: always
        restart: yes
        ports:
          - 80:3000 # Change this
          - 443:443
        volumes:
          - /monitoring/nginx/nginx.conf:/etc/nginx/nginx.conf
          - /monitoring/nginx/certs:/etc/certs

